[phases.setup]
nixPkgs = ["pnpm"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]
cacheDirectories = ["node_modules", "apps/storefront/node_modules", "apps/backend/node_modules"]

[phases.build]
cmds = [
  "pnpm install --frozen-lockfile",
  "pnpm turbo build --filter=medusa-2.0-boilerplate-backend",
  "cd apps/backend && init-backend && medusa db:migrate",
]
cacheDirectories = [
  "apps/storefront/.next/cache",
  "apps/backend/.medusa",
  "packages/plugin-email/.medusa",
  "packages/plugin-invoices/.medusa",
  "packages/plugin-loyalty/.medusa",
  "packages/plugin-reviews/.medusa",
  "packages/plugin-bundles/.medusa",
  "packages/plugin-preorder/.medusa",
  "packages/plugin-shipstation/.medusa",
  "packages/plugin-subscription/.medusa",
  # "packages/plugin-qr-marketing/.medusa", -- removed to force rebuild with new migration
]

[start]
cmd = "cd apps/backend/.medusa/server && medusa start --verbose"
